[package]
name = "ingo_skyscrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
primitive-types = "0.12"

[profile.release]
debug = true
lto = false

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "bench"
harness = false
